---
layout: post
title: "How to build a website with Asciidoctor"
excerpt: "Build a website with one command using only Asciidoctor..."
tags: [featured, AsciiDoc, Asciidoctor]
comments: true
---

Take a look at this demo of website I made _only using Asciidoctor_ and with *one command*. http://tedbergeron.github.io/SiteMadeWithAsciidoctor/

== How To
Start by downloading the files in my link:https://github.com/tedbergeron/SiteMadeWithAsciidoctor[GitHub Repo]sitory.
Edit the content in the text files marking them up with AsciiDoc.

I am using a header and footer that is included on the index and page one AsciiDoc text file.

== To render the pages

At the command prompt

 > asciidoctor *.txt

== Push or FTP

Push your files back to your GitHub 'gh-pages' branch.

Or just FTP the .html files that were generated to your own website.

== That's it, you're done.

Following is some additional information to customize your website.


==== Use Different Asciidoctor Themes

I've included a couple themes in the styles directory in the repository. To use them.

At the command prompt

 > asciidoctor -a stylesheet=styles/maker.css  *.txt

If you'd like to use the colony stylesheet use

 > asciidoctor -a stylesheet=styles/colony.css  *.txt


NOTE: You can get other themes and preview them here: http://themes.asciidoctor.org/


==== Smart Links

I'm using Asciidoctor 'smart links' to convert the file extension ".adoc" or ".txt" to ".html"

 <<page2.adoc#,Smart Link to page 2>>
 or
 <<page2.txt#,Smart Link to page 2>>

both renders as a link

 href="page2.html"

==== Ignore the Extra Files

This method will render the header.txt and footer.txt into html files too. But since they're not linked to anything, it's fine for them to live along side the others.

You could get organized and put all the Asciidoc text files into a sub-directory, but I'll leave that to you to figure out the logistics.

My goal was to generate the simplest website using the most minimal command.


==== Why don't you use .adoc files?

Typically you see AsciiDoc files with an .adoc or .asciidoc file extension. But since they are just text files and since Asciidoctor will try to render any text file you feed it, I choose to use .txt so people can easily edit the files in Notepad.


==== Additional Info

* link:http://asciidoctor.org/docs/what-is-asciidoc/[What is AsciiDoc?]
* link:http://asciidoctor.org/docs/#get-started-with-asciidoctor[Get Started with Asciidoctor]
